# Copyright (c) 2026 Codium Electronique
# Copyright (c) 2026 Deveritec GmbH
# SPDX-License-Identifier: Apache-2.0

CONFIG_KERNEL_BIN_NAME="sample-dectnrp-driver"
CONFIG_NCS_APPLICATION_BOOT_BANNER_STRING="sample-dectnrp-driver"

#Enable thread awareness for debugging tools supporting it
CONFIG_DEBUG_THREAD_INFO=y
CONFIG_ASSERT=y

CONFIG_TFM_PROFILE_TYPE_MINIMAL=y

CONFIG_NETWORKING=y
CONFIG_NET_L2_DUMMY=y

CONFIG_HWINFO=y
CONFIG_LOG=y
CONFIG_USE_SEGGER_RTT=y
CONFIG_LOG_BACKEND_RTT=y
CONFIG_SEGGER_RTT_BUFFER_SIZE_UP=4096
CONFIG_LOG_BACKEND_RTT_MODE_OVERWRITE=y

CONFIG_DECTNRP_DRIVER_NRF91=y
CONFIG_DECTNRP_DRIVER_NRF91_CAP_LOGGING=n
CONFIG_DECTNRP_DRIVER_SCHEDULED_API=y
CONFIG_DECTNRP_DRIVER_BLOCKING_API=n

CONFIG_SAMPLE_DRIVER_DECTNRP_LOG_LEVEL_DBG=n
CONFIG_SAMPLE_DRIVER_DECTNRP_LOG_LEVEL_INF=y
CONFIG_DECTNRP_SAMPLE_NETWORK_ID=0x32545279
CONFIG_DECTNRP_SAMPLE_CHANNEL=1677
CONFIG_DECTNRP_SAMPLE_PERIOD=3000




