# Copyright (c) 2026 Codium Electronique
# SPDX-License-Identifier: Apache-2.0

CONFIG_TFM_PROFILE_TYPE_MINIMAL=y

CONFIG_NETWORKING=y
CONFIG_NET_L2_DUMMY=y

CONFIG_HWINFO=y
CONFIG_LOG=y

CONFIG_DECTNRP_DRIVER_BLOCKING_API=y
CONFIG_SAMPLE_DRIVER_DECTNRP_LOG_LEVEL_DBG=y